# Week 2 Day Lab

### Problem 1: Installing NumPy

If not already installed, install the numpy library using `!pip install numpy`. After installing, import numpy with variable name `np`.

In [5]:

import numpy as np
import math

### Problem 2: Installing other libraries
We will use other libraries throughout this semester as well. Here are a couple:

    - matplotlib
    - networkx
    - pandas
    - geopandas
Try importing these libraries. If they are not installed, use `pip install` to install them for future use.

In [6]:
!pip install matplotlib
!pip install networkx
!pip install pandas
!pip install geopandas

   ---------------------------------------- 0.0/23.8 MB ? eta -:--:--
   ----- ---------------------------------- 3.1/23.8 MB 16.2 MB/s eta 0:00:02
   ---------- ----------------------------- 6.3/23.8 MB 15.3 MB/s eta 0:00:02
   --------------- ------------------------ 9.4/23.8 MB 15.0 MB/s eta 0:00:01
   -------------------- ------------------- 12.1/23.8 MB 14.4 MB/s eta 0:00:01
   ------------------------- -------------- 15.2/23.8 MB 14.4 MB/s eta 0:00:01
   ------------------------------ --------- 18.4/23.8 MB 14.6 MB/s eta 0:00:01
   ------------------------------------ --- 22.0/23.8 MB 14.8 MB/s eta 0:00:01
   ---------------------------------------  23.6/23.8 MB 14.9 MB/s eta 0:00:01
   ---------------------------------------- 23.8/23.8 MB 13.5 MB/s  0:00:01
   ---------------------------------------- 0.0/6.3 MB ? eta -:--:--
   ------------------- -------------------- 3.1/6.3 MB 15.0 MB/s eta 0:00:01
   ---------------------------------------  6.3/6.3 MB 15.6 MB/s eta 0:00:01
  

### Problem 3

Given

```python
a = np.array([2, 4, 6, 8])
```

compute each of the following:

1. a + 3
2. 2 * a
3. a**2
4. a - 1

Do not use a `for` loop.


In [9]:
a = np.array([2, 4, 6, 8])
print(a + 3)
print(2 * a)
print(a**2)
print(a-1)

[ 5  7  9 11]
[ 4  8 12 16]
[ 4 16 36 64]
[1 3 5 7]


### Problem 4

The derivative of a function \(f(x)\) at a point \(x\) is defined as the limit

$
f'(x)=\lim_{h\to0}\frac{f(x+h)-f(x)}{h}
$

provided the limit exists.

Define a function $g(h)$ that computes the quotient above for a given function $f$ near a point $x$. Then, vectorize $g$. 


Using `np.linspace()`, let $f(x)=sin(x)$ and compute $g$ at $10^{-1}, 10^{-2}, 10^{-3}, 10^{-4}$. This will be an estimate for the derivative of $f$. Compare to the actual derivative.

In [55]:
def f(x):
    return np.sin(x)
def g(h):
    return((f(x+h) - f(x)/h))

G = np.vectorize(g)

h = 10**np.linspace(-1, -4, 4)


exact = np.cos(x)

print(G(h))
print(exact)

[9.98334166e-02 9.99983333e-03 9.99999833e-04 9.99999998e-05]
1.0


###  Problem 5
Let

$
A=
\begin{bmatrix}
2 & 1 \\
3 & 4
\end{bmatrix},
\qquad
B=
\begin{bmatrix}
5 & 2 \\
1 & 6
\end{bmatrix}
$

Compute the product.

In [12]:
A = np.array([2, 1, 3, 4])
B = np.array([5, 2, 1, 6])
A = A.reshape(2, 2)
B = B.reshape(2,2)
print(A*B)


[[10  2]
 [ 3 24]]
